### ISSUE TITLE
Doing a cross tenant PowerBI integration, everything worked until reaching Set-AzDataCatalogSessionSettings. Here it fails

### ISSUE THREAD

**Issue by constantino-casado** [Azure/Purview-Samples#14]
VERBOSE: Exception Details - System.TypeInitializationException: The type initializer for
'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception. --->
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Microsoft.DataCatalog.Management.Commands.Commands.IntegrationRuntimeClient..ctor()
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager.ResetIntegrationRuntimeClient()
   at Microsoft.DataCatalog.Management.Commands.SetSessionSettingsCmdlet.ExecuteCmdlet()
   at Microsoft.DataCatalog.Management.Commands.DataCatalogCmdletBase.ProcessRecord()
Set-AzDataCatalogSessionSettings : The type initializer for
'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception.
At line:1 char:1
+ Set-AzDataCatalogSessionSettings -TenantId '72f988bf-86f1-41af-91ab-2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzDataCatalogSessionSettings], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.DataCatalog.Management.Commands.SetSessionS
   ettingsCmdlet

**Comment by cggarmendiaencamina** [comment]
I have the same problem when I try to perform the following steps to register and scan one or more Power BI tenants in Azure Purview in a cross-tenant scenario: https://docs.microsoft.com/en-us/azure/purview/register-scan-power-bi-tenant#register-and-scan-a-cross-tenant-power-bi. I'm stuck at step 12.

`
Set-AzDataCatalogSessionSettings : The type initializer for 'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception.
At line:1 char:1
+ Set-AzDataCatalogSessionSettings -DataCatalogSession -TenantId $azure ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzDataCatalogSessionSettings], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.DataCatalog.Management.Commands.SetSessionSettingsCmdlet

VERBOSE: Exception Details - System.Exception: Session is not initialized. Run 'Set-AzDataCatalogSessionSettings' cmdlet to initialize the session before running the Data Catalog cmdlets.
   at Microsoft.DataCatalog.Management.Commands.DataCatalogCmdletBase.ProcessRecord()
Set-AzDataCatalogDataSource : Session is not initialized. Run 'Set-AzDataCatalogSessionSettings' cmdlet to initialize the session before running the Data Catalog cmdlets.
At line:3 char:1
+ Set-AzDataCatalogDataSource -Name 'pbidatasource' -AccountType PowerB ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzDataCatalogDataSource], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.DataCatalog.ManagedScan.DataSource.SetAzDataCatalogDataSource
`

**Comment by tuterbatuhan** [comment]
**Same  issue here!**

Running the code:

` Set-AzDataCatalogSessionSettings -DataCatalogSession -ServicePrincipalAuthentication -TenantId $azuretenantId -ServicePrincipalApplicationId $ServicePrincipalId -ServicePrincipalKey $ServicePrincipalKey -DataCatalogAccountName $purviewaccount -Verbose`

Received Error:

`VERBOSE: Exception Details - System.TypeInitializationException: The type initializer for 'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception. --->
 System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Microsoft.DataCatalog.Management.Commands.Commands.IntegrationRuntimeClient..ctor()
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager.ResetIntegrationRuntimeClient()
   at Microsoft.DataCatalog.Management.Commands.SetSessionSettingsCmdlet.ExecuteCmdlet()
   at Microsoft.DataCatalog.Management.Commands.DataCatalogCmdletBase.ProcessRecord()
Set-AzDataCatalogSessionSettings : The type initializer for 'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception.
At line:1 char:1
+ Set-AzDataCatalogSessionSettings -DataCatalogSession -ServicePrincipa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzDataCatalogSessionSettings], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.DataCatalog.Management.Commands.SetSessionSettingsCmdlet`

**Comment by ds-porini** [comment]
Same issue also here!

**Powershell command:**
Set-AzDataCatalogSessionSettings -DataCatalogSession -TenantId $azuretenantId -ServicePrincipalAuthentication -ServicePrincipalApplicationId $ServicePrincipalId -ServicePrincipalKey $ServicePrincipalKey -DataCatalogAccountName $purviewaccount -verbose

**Output:**
VERBOSE: Exception Details - System.TypeInitializationException: The type initializer for
'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception. --->
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Microsoft.DataCatalog.Management.Commands.Commands.IntegrationRuntimeClient..ctor()
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager.ResetIntegrationRuntimeClient()
   at Microsoft.DataCatalog.Management.Commands.SetSessionSettingsCmdlet.ExecuteCmdlet()
   at Microsoft.DataCatalog.Management.Commands.DataCatalogCmdletBase.ProcessRecord()
Set-AzDataCatalogSessionSettings : The type initializer for
'Microsoft.DataCatalog.Management.Commands.DataFactoryClientManager' threw an exception.
At line:1 char:1
+ Set-AzDataCatalogSessionSettings -DataCatalogSession -TenantId $azure ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzDataCatalogSessionSettings], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.DataCatalog.Management.Commands.SetSessionSe
   ttingsCmdlet

**Comment by tuterbatuhan** [comment]
I solved the problem. Please check your Service Principal's API permissions.  It needs to have **DELEGATED** permissions.  In my case, I had given **Application** permissions. See section 8.b in [documentation](https://docs.microsoft.com/en-us/azure/purview/register-scan-power-bi-tenant#steps-to-register-cross-tenant) for the details.
